# Generated by Django 3.1.3 on 2020-12-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20201206_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
