# Generated by Django 3.1.3 on 2020-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_user_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='assignees',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_to', to='flow.User'),
        ),
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='cards_labeled', to='flow.Tag'),
        ),
    ]
