# Generated by Django 3.1.3 on 2020-12-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_auto_20201209_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='creator',
            new_name='owner',
        ),
    ]
